version: 2
workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - build-production:
          filters:
            branches:
              ignore:
                - master
jobs:
  build:
    docker:
      - image: darthjee/circleci_plague_inc-base:0.0.1
        environment:
          PLAGUE_INC_MYSQL_HOST: mysql
          PLAGUE_INC_MYSQL_PORT: 3306
          PLAGUE_INC_MYSQL_USER: plague_inc
          PLAGUE_INC_MYSQL_NAME: plague_inc
          PLAGUE_INC_MYSQL_PASSWORD: plague_inc
          PLAGUE_INC_PASSWORD_SALT: abcd
      - image: circleci/mysql:5.7
        name: mysql
        environment:
          MYSQL_DATABASE: plague_inc_test
          MYSQL_USER: plague_inc
          MYSQL_PASSWORD: plague_inc
    steps:
      - checkout
      - run:
          name: Set folder
          command: cp source/* source/.??* ./ -r; rm source -rf
      - run:
          name: Prepare Coverage Test Report
          command: cc-test-reporter before-build
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Bower Install
          command: bundle exec rake bower:install
      - run:
          name: Rubocop
          command: rubocop
      - run:
          name: Wait for database
          command: scripts/wait_for_db.sh
      - run:
          name: Migrate
          command: RAILS_ENV=test bundle exec rake db:schema:load
      - run:
          name: RSpec
          command: bundle exec rspec
      - run:
          name: Coverage Test Report
          command: cc-test-reporter after-build --exit-code $?
  build-production:
    machine: true
    steps:
      - checkout
      - run:
          name: Make Build
          command: make PROJECT=production_plague_inc build
